name: pizza_app_admin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.6
  go_router: ^10.1.2

  #Bloc
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  #Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  firebase_auth_web: ^5.1.3

  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
